name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Rsync deployments
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avztru --delete --exclude '.*' --exclude '*.ps' --checksum --no-times
        path: .
        remote_path: /LARGE0/gr10291/nishimori2
        remote_host: laurel.kudpc.kyoto-u.ac.jp
        remote_user: b36156
        remote_key: ${{ secrets.DEPLOY_KEY }}
        remote_port: 22
        